motdChangerSettings:
  line1: ""
  line2: ""

deathBoxSettings:
  replaceBlocks:
    - "AIR"
    - "SNOW"
    - "GRASS"
    - "TALL_GRASS"
    - "SEAGRASS"
    - "TALL_SEAGRASS"
    - "TORCH"
    - "WATER"
