main: xyz.garslity093.RealmCore.PluginCore
name: RealmCore
version: 1.1.0
author: Gerry5126
api-version: 1.13
commands:
  realmcore:
    aliases:
      - rc
      - core
    permission: "realmcore.use"
